### PR TITLE
Add Postal Mail Service

### PR DESCRIPTION
**Pull request by rubenmuehlhans**
This adds Support for Postal (https://github.com/postalhq/postal) Mail Service.
Postal is a self hosted, open source mailserver like Sendgrid or Mailgun.

### CODE REVIEW

**Comment by mauricius** [comment]
Can you please add a migration for the new email service type? Something like this would work

```
class AddPostalEmailServiceType extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::table('sendportal_email_service_types')
            ->insert(
                [
                    'id' => EmailServiceType::Postal,
                    'name' => 'Postal',
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
    }
}
```

Also can you please remove the `.DS_Store` file from your PR?

Thank you!

**Comment by c-perez** [comment]
Hello

Will this feature be released any time soon?
What can be done to speed up a bit the process?

Excellent work with sendportal.
Thank you.

**Comment by JonoB** [comment]
Happy to merge if we can get a few people to test that its all working correctly

**Comment by c-perez** [comment]
I just found the same issue that @donatid 

Migrating: 2021_10_22_202820_add_postal_email_service_type

Error

Undefined class constant 'Postal'

at vendor/mettle/sendportal-core/database/migrations/2021_10_22_202820_add_postal_email_service_type.php:19
15▕ {
16▕ DB::table('sendportal_email_service_types')
17▕ ->insert(
18▕ [
➜ 19▕ 'id' => EmailServiceType::Postal,
20▕ 'name' => 'Postal',
21▕ 'created_at' => now(),
22▕ 'updated_at' => now(),
23▕ ]


I manually changed to POSTAL to keep testing.

php artisan sp:upgrade  ---> RUN OK

Messages are been sent correctly.
Webhooks (Delivery, Open, Bounce, and Clicks) events are working as expected.

https://i.imgur.com/DXrpao5.png
https://i.imgur.com/kecftz4.png

**Comment by rubenmuehlhans** [comment]
sorry guys, must be blind on that uppercase eye

**Review by c-perez — APPROVED** [review]

**Comment by mauricius** [comment]
@rubenmuehlhans can you please align your branch to the latest changes on master? Hopefully that would solve the php-cs-fixer issue...

**Comment by rubenmuehlhans** [comment]
@mauricius done

**Comment by JonoB** [comment]
Thanks for the work on this @rubenmuehlhans and those who tested!

**Pull request merged**
